baseURL: "https://ristrettorambles.com/"
title: RistrettoRambles	
paginate: 5
theme: hugo-PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
# googleAnalytics: UA-123-45

minify:
    disableXML: true
    # minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        menu:
            main:
                - name: About
                  url: about
                  weight: 5
                - name: RistreDatabase
                  url: ristredatabase
                  weight: 10
                - name: Archive
                  url: archives
                  weight: 15
                - name: Search
                  url: search/
                  weight: 20
                #- name: Tags
                  #url: tags/
                  #weight: 10
                #- name: Categories
                  #url: categories/
                  #weight: 10

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "Rambles from Ristretto, in blog form."
    author: Ristretto
    # author: ["Ristretto", "You"] # multiple authors

    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: true
    disableSpecial1stPost: true
    displayFullLangName: true
    #ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true
    # comments: false
    # images: ["papermod-cover.png"]

    profileMode:
        enabled: false
        title: RistrettoRambles
        imageUrl: "/icon.png"
        imageTitle: my image
         #imageWidth: 72
         #imageHeight: 72
        buttons:
            - name: Archives
              url: archives
            - name: Tags
              url: tags

    homeInfoParams:
        #Title: "RistrettoRambles"
        Content: >
            ## Ahoy & Cheers!

            ---

            - Welcome to my 'freshly brewed' personal site. 

            - Here you'll find my bits of writing, current projects, a small writeup about myself, and links to other profiles of mine around the 'net. 
          
            --- 

            - Thanks for visiting!

    socialIcons:
        - name: twitch
          url: "http://twitch.tv/ristrettorambles/"
        - name: discord
          url: "https://discord.gg/f2QmzbH"
        - name: twitter
          url: "https://twitter.com/ristrettogames/"
        - name: youtube
          url: "https://www.youtube.com/channel/UCgg0KncWzZobxuy3nO0xRuQ"
        #- name: RsS
          #url: "index.xml"

    #editPost:
        #URL: "https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite/content"
        #Text: "Suggest Changes" # edit text
        #appendFilePath: true # to append file path to Edit link

label:
   text: "Home"
   icon: "/icon.png"
   iconHeight: 35

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"

assets:
    favicon: "/favicon.ico"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-32x32.ico"
    apple_touch_icon: "/apple-touch-icon.png"
        # safari_pinned_tab: "<link / abs url>"

cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

#fuseOpts:
    #isCaseSensitive: false
    #shouldSort: true
    #location: 0
    #distance: 1000
    #threshold: 0.4
    #minMatchCharLength: 0
    #keys: ["title", "permalink", "summary", "content"]

taxonomies:
    category: categories
    tag: tags
    series: series

markup:
    goldmark:
        renderer:
            unsafe: true
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         # noClasses: false
#         style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
